/* eslint-disable prettier/prettier */
export enum FeesNames {
  oLevelApplicationFee = 'oLevelApplicationFee',
  aLevelApplicationFee = 'aLevelApplicationFee',
  admissionFee = 'admissionFee',
  oLevelTuitionDay = 'oLevelTuitionDay',
  aLevelTuitionDay = 'aLevelTuitionDay',
  oLevelTuitionBoarder = 'oLevelTuitionBoarder',
  aLevelTuitionBoarder = 'aLevelTuitionBoarder',
  oLevelScienceFee = 'oLevelScienceFee',
  alevelScienceFee = 'aLevelScienceFee',
  developmentFee = 'developmentFee',
  foodFee = 'foodFee',
  transportFee = 'transportFee',
  juniorGirlsUniform = 'juniorGirlsUniform',
  juniorBoysUniform = 'juniorBoysUniform',
  seniorGirlsUniform = 'seniorGirlsUniform',
  seniorBoysUniform = 'seniorBoysUniform',
  exemption = 'exemption',
}
